server:
  port: 7002
spring:
  application:
    name: upload-service
    service:
      multipart:
        max-file-size: 5MB # 限制文件上传的大小
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
